name: test-cov

on:
  push:
    branches:
      - main
jobs:
  Testing-Report:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20.x

      - name: install dependencies
        run: npm i
      - name: Run Unit Test
        run: npm run test:report

      - name: Test Report
        id: test-report
        uses: dorny/test-reporter@v1.7.0
        if: success() || failure()
        with:
          name: test-results
          path: junit.xml
          fail-on-error: 'false'
          reporter: jest-junit
          token: ${{ secrets.GITHUB_TOKEN }}
