name: test-cov

on:
  push:
    branches:
      - main

jobs:
  Dev-Testing:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        test-suite: [test:app, test:user] # 병렬로 실행할 테스트 스크립트

    permissions:
      contents: read
      actions: read
      checks: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20.x

      - name: install dependencies
        run: npm ci

      - name: Run Unit Test for ${{ matrix.test-suite }}
        run: npm run ${{ matrix.test-suite }}

      - name: Store test results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.test-suite }}-result
          path: junit-${{ matrix.test-suite }}.xml
