name: test-cov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Testing:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      actions: read
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Test
        run: npm run test:report

      - name: Upload Test Report
        id: test-report
        uses: dorny/test-reporter@v1.7.0
        if: success() || failure()
        with:
          name: test-results
          path: junit.xml
          fail-on-error: 'false'
          reporter: jest-junit
          token: ${{ secrets.GITHUB_TOKEN }}
