name: 'coverage'
on:
  push:
    branches:
      - master
      - main

jobs:
  coverage:
    permissions:
      contents: write
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json
          package-manager: npm
          coverage-file: report.json
          base-coverage-file: report.json

        # npx jest --ci --json --coverage --testLocationInResults --outputFile=report.json
